# Generated by Django 4.2.23 on 2025-06-18 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifferenceDividedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=255)),
                ('x_value', models.FloatField()),
                ('h_value', models.FloatField()),
                ('derivada_fwd', models.FloatField()),
                ('formula_fwd', models.TextField()),
                ('pasos_fwd', models.TextField()),
                ('derivada_bwd', models.FloatField()),
                ('formula_bwd', models.TextField()),
                ('pasos_bwd', models.TextField()),
                ('derivada_cen', models.FloatField()),
                ('formula_cen', models.TextField()),
                ('pasos_cen', models.TextField()),
                ('derivada_exacta', models.FloatField()),
                ('error_fwd', models.FloatField()),
                ('error_bwd', models.FloatField()),
                ('error_cen', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
