# Generated by Django 4.2.23 on 2025-06-22 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DifferenceDividedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.TextField(help_text="Función matemática en formato de texto, ej. 'x**2 + 3*x'")),
                ('x_value', models.FloatField(verbose_name='Valor de x')),
                ('h_value', models.FloatField(verbose_name='Valor de h (incremento)')),
                ('derivada_forward', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('derivada_backward', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('derivada_central', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('derivada_exacta', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('formula_forward', models.TextField(blank=True)),
                ('pasos_forward', models.TextField(blank=True)),
                ('formula_backward', models.TextField(blank=True)),
                ('pasos_backward', models.TextField(blank=True)),
                ('formula_central', models.TextField(blank=True)),
                ('pasos_central', models.TextField(blank=True)),
                ('error_forward', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('error_backward', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('error_central', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differentiation_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Diferenciación',
                'verbose_name_plural': 'Historiales de Diferenciación',
                'ordering': ['-created_at'],
            },
        ),
    ]
