# Generated by Django 5.2.2 on 2025-06-14 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialNewton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_x', models.TextField()),
                ('puntos_y', models.TextField()),
                ('polinomio', models.TextField()),
                ('valor_evaluado', models.FloatField()),
                ('resultado', models.FloatField()),
                ('pasos', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
