# Generated by Django 5.2.2 on 2025-06-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodo_df_divididas', '0002_remove_historialnewton_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialnewton',
            name='resultado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialnewton',
            name='valor_evaluado',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
